IF OBJECT_ID(N'dbo.MoveAdvisorUsers', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.MoveAdvisorUsers (
    Id NVARCHAR(64) NOT NULL PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordSalt NVARCHAR(64) NOT NULL,
    PasswordHash NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2 NOT NULL,
    LastLoginAt DATETIME2 NOT NULL
  );

  CREATE UNIQUE INDEX IX_MoveAdvisorUsers_Email ON dbo.MoveAdvisorUsers (Email);
END;
-- BEGIN VEHICLE CATALOG SCHEMA
IF OBJECT_ID(N'dbo.MoveAdvisorVehicleBrands', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.MoveAdvisorVehicleBrands (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_MoveAdvisorVehicleBrands_IsActive DEFAULT (1),
    SortOrder INT NOT NULL CONSTRAINT DF_MoveAdvisorVehicleBrands_SortOrder DEFAULT (0)
  );

  CREATE UNIQUE INDEX IX_MoveAdvisorVehicleBrands_Name ON dbo.MoveAdvisorVehicleBrands (Name);
END;

IF OBJECT_ID(N'dbo.MoveAdvisorVehicleModels', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.MoveAdvisorVehicleModels (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    BrandId INT NOT NULL,
    Name NVARCHAR(120) NOT NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_MoveAdvisorVehicleModels_IsActive DEFAULT (1),
    SortOrder INT NOT NULL CONSTRAINT DF_MoveAdvisorVehicleModels_SortOrder DEFAULT (0),
    CONSTRAINT FK_MoveAdvisorVehicleModels_Brand FOREIGN KEY (BrandId) REFERENCES dbo.MoveAdvisorVehicleBrands(Id)
  );

  CREATE UNIQUE INDEX IX_MoveAdvisorVehicleModels_BrandId_Name ON dbo.MoveAdvisorVehicleModels (BrandId, Name);
END;
-- END VEHICLE CATALOG SCHEMA
-- BEGIN VEHICLE CATALOG SEED
-- Seed catalogo marcas/modelos (idempotente)
DECLARE @BrandSeed TABLE (Name NVARCHAR(100), SortOrder INT);
INSERT INTO @BrandSeed (Name, SortOrder) VALUES
  (N'Alfa Romeo', 1),
  (N'Audi', 2),
  (N'BMW', 3),
  (N'BYD', 4),
  (N'Citroen', 5),
  (N'Cupra', 6),
  (N'Toyota', 7),
  (N'DS', 8),
  (N'Dacia', 9),
  (N'Fiat', 10),
  (N'Ford', 11),
  (N'Honda', 12),
  (N'Hyundai', 13),
  (N'Jaecoo', 14),
  (N'Jaguar', 15),
  (N'Jeep', 16),
  (N'Kia', 17),
  (N'Lexus', 18),
  (N'Land Rover', 19),
  (N'LynkCo', 20),
  (N'Mazda', 21),
  (N'Renault', 22),
  (N'Mercedes', 23),
  (N'MG', 24),
  (N'Mini', 25),
  (N'Mitsubishi', 26),
  (N'Nissan', 27),
  (N'Omoda', 28),
  (N'Opel', 29),
  (N'Peugeot', 30),
  (N'Polestar', 31),
  (N'Porsche', 32),
  (N'Seat', 33),
  (N'Skoda', 34),
  (N'Smart', 35),
  (N'Subaru', 36),
  (N'Suzuki', 37),
  (N'Tesla', 38),
  (N'Volvo', 39),
  (N'Volkswagen', 40),
  (N'XPeng', 41);

MERGE dbo.MoveAdvisorVehicleBrands AS target
USING @BrandSeed AS source
ON target.Name = source.Name
WHEN MATCHED THEN UPDATE SET target.SortOrder = source.SortOrder, target.IsActive = 1
WHEN NOT MATCHED THEN INSERT (Name, SortOrder, IsActive) VALUES (source.Name, source.SortOrder, 1);

DECLARE @ModelSeed TABLE (BrandName NVARCHAR(100), ModelName NVARCHAR(120), SortOrder INT);
INSERT INTO @ModelSeed (BrandName, ModelName, SortOrder) VALUES
  (N'Alfa Romeo', N'Giulia', 1),
  (N'Alfa Romeo', N'Stelvio', 2),
  (N'Alfa Romeo', N'Tonale', 3),
  (N'Alfa Romeo', N'Junior', 4),
  (N'Audi', N'A1', 1),
  (N'Audi', N'A3', 2),
  (N'Audi', N'Q2', 3),
  (N'Audi', N'Q3', 4),
  (N'BMW', N'Serie 1', 1),
  (N'BMW', N'Serie 3', 2),
  (N'BMW', N'X1', 3),
  (N'BMW', N'X3', 4),
  (N'BYD', N'Atto 3', 1),
  (N'BYD', N'Dolphin', 2),
  (N'BYD', N'Seal', 3),
  (N'BYD', N'Seal U', 4),
  (N'Citroen', N'C3', 1),
  (N'Citroen', N'C4', 2),
  (N'Citroen', N'C5 Aircross', 3),
  (N'Citroen', N'Berlingo', 4),
  (N'Cupra', N'Born', 1),
  (N'Cupra', N'Formentor', 2),
  (N'Cupra', N'Leon', 3),
  (N'Cupra', N'Terramar', 4),
  (N'Toyota', N'Corolla', 1),
  (N'Toyota', N'C-HR', 2),
  (N'Toyota', N'Yaris', 3),
  (N'Toyota', N'RAV4', 4),
  (N'DS', N'DS 3', 1),
  (N'DS', N'DS 4', 2),
  (N'DS', N'DS 7', 3),
  (N'DS', N'DS 9', 4),
  (N'Dacia', N'Sandero', 1),
  (N'Dacia', N'Duster', 2),
  (N'Dacia', N'Jogger', 3),
  (N'Dacia', N'Spring', 4),
  (N'Fiat', N'500', 1),
  (N'Fiat', N'600', 2),
  (N'Fiat', N'Tipo', 3),
  (N'Fiat', N'Panda', 4),
  (N'Ford', N'Fiesta', 1),
  (N'Ford', N'Focus', 2),
  (N'Ford', N'Kuga', 3),
  (N'Ford', N'Puma', 4),
  (N'Honda', N'Civic', 1),
  (N'Honda', N'HR-V', 2),
  (N'Honda', N'CR-V', 3),
  (N'Honda', N'Jazz', 4),
  (N'Hyundai', N'i20', 1),
  (N'Hyundai', N'i30', 2),
  (N'Hyundai', N'Kona', 3),
  (N'Hyundai', N'Tucson', 4),
  (N'Jaecoo', N'J7', 1),
  (N'Jaecoo', N'J8', 2),
  (N'Jaecoo', N'J7 PHEV', 3),
  (N'Jaecoo', N'J8 PHEV', 4),
  (N'Jaguar', N'E-Pace', 1),
  (N'Jaguar', N'F-Pace', 2),
  (N'Jaguar', N'XE', 3),
  (N'Jaguar', N'I-Pace', 4),
  (N'Jeep', N'Avenger', 1),
  (N'Jeep', N'Compass', 2),
  (N'Jeep', N'Renegade', 3),
  (N'Jeep', N'Grand Cherokee', 4),
  (N'Kia', N'Ceed', 1),
  (N'Kia', N'Niro', 2),
  (N'Kia', N'Sportage', 3),
  (N'Kia', N'EV6', 4),
  (N'Lexus', N'UX', 1),
  (N'Lexus', N'NX', 2),
  (N'Lexus', N'RX', 3),
  (N'Lexus', N'LBX', 4),
  (N'Land Rover', N'Range Rover Evoque', 1),
  (N'Land Rover', N'Range Rover Velar', 2),
  (N'Land Rover', N'Discovery Sport', 3),
  (N'Land Rover', N'Defender', 4),
  (N'LynkCo', N'01', 1),
  (N'LynkCo', N'02', 2),
  (N'LynkCo', N'03', 3),
  (N'LynkCo', N'08', 4),
  (N'Mazda', N'Mazda2', 1),
  (N'Mazda', N'Mazda3', 2),
  (N'Mazda', N'CX-30', 3),
  (N'Mazda', N'CX-5', 4),
  (N'Renault', N'Clio', 1),
  (N'Renault', N'Captur', 2),
  (N'Renault', N'Megane', 3),
  (N'Renault', N'Austral', 4),
  (N'Mercedes', N'Clase A', 1),
  (N'Mercedes', N'Clase C', 2),
  (N'Mercedes', N'GLA', 3),
  (N'Mercedes', N'GLC', 4),
  (N'MG', N'ZS', 1),
  (N'MG', N'HS', 2),
  (N'MG', N'MG4', 3),
  (N'MG', N'Marvel R', 4),
  (N'Mini', N'Cooper', 1),
  (N'Mini', N'Countryman', 2),
  (N'Mini', N'Aceman', 3),
  (N'Mini', N'Clubman', 4),
  (N'Mitsubishi', N'ASX', 1),
  (N'Mitsubishi', N'Eclipse Cross', 2),
  (N'Mitsubishi', N'Outlander', 3),
  (N'Mitsubishi', N'Space Star', 4),
  (N'Nissan', N'Micra', 1),
  (N'Nissan', N'Qashqai', 2),
  (N'Nissan', N'X-Trail', 3),
  (N'Nissan', N'Juke', 4),
  (N'Omoda', N'Omoda 5', 1),
  (N'Omoda', N'Omoda 5 EV', 2),
  (N'Omoda', N'Omoda 7', 3),
  (N'Omoda', N'Omoda 9', 4),
  (N'Opel', N'Corsa', 1),
  (N'Opel', N'Astra', 2),
  (N'Opel', N'Mokka', 3),
  (N'Opel', N'Grandland', 4),
  (N'Peugeot', N'208', 1),
  (N'Peugeot', N'2008', 2),
  (N'Peugeot', N'308', 3),
  (N'Peugeot', N'3008', 4),
  (N'Polestar', N'Polestar 2', 1),
  (N'Polestar', N'Polestar 3', 2),
  (N'Polestar', N'Polestar 4', 3),
  (N'Polestar', N'Polestar 5', 4),
  (N'Porsche', N'Macan', 1),
  (N'Porsche', N'Cayenne', 2),
  (N'Porsche', N'Taycan', 3),
  (N'Porsche', N'Panamera', 4),
  (N'Seat', N'Ibiza', 1),
  (N'Seat', N'Leon', 2),
  (N'Seat', N'Arona', 3),
  (N'Seat', N'Ateca', 4),
  (N'Skoda', N'Fabia', 1),
  (N'Skoda', N'Octavia', 2),
  (N'Skoda', N'Kamiq', 3),
  (N'Skoda', N'Kodiaq', 4),
  (N'Smart', N'fortwo', 1),
  (N'Smart', N'forfour', 2),
  (N'Smart', N'Smart 1', 3),
  (N'Smart', N'Smart 3', 4),
  (N'Subaru', N'Impreza', 1),
  (N'Subaru', N'XV', 2),
  (N'Subaru', N'Forester', 3),
  (N'Subaru', N'Outback', 4),
  (N'Suzuki', N'Swift', 1),
  (N'Suzuki', N'Vitara', 2),
  (N'Suzuki', N'S-Cross', 3),
  (N'Suzuki', N'Across', 4),
  (N'Tesla', N'Model 3', 1),
  (N'Tesla', N'Model Y', 2),
  (N'Tesla', N'Model S', 3),
  (N'Tesla', N'Model X', 4),
  (N'Volvo', N'XC40', 1),
  (N'Volvo', N'XC60', 2),
  (N'Volvo', N'S60', 3),
  (N'Volvo', N'V60', 4),
  (N'Volkswagen', N'Polo', 1),
  (N'Volkswagen', N'Golf', 2),
  (N'Volkswagen', N'T-Roc', 3),
  (N'Volkswagen', N'Tiguan', 4),
  (N'XPeng', N'G6', 1),
  (N'XPeng', N'G9', 2),
  (N'XPeng', N'P7', 3),
  (N'XPeng', N'X9', 4);

MERGE dbo.MoveAdvisorVehicleModels AS target
USING (
  SELECT b.Id AS BrandId, s.ModelName, s.SortOrder
  FROM @ModelSeed s
  INNER JOIN dbo.MoveAdvisorVehicleBrands b ON b.Name = s.BrandName
) AS source
ON target.BrandId = source.BrandId AND target.Name = source.ModelName
WHEN MATCHED THEN UPDATE SET target.SortOrder = source.SortOrder, target.IsActive = 1
WHEN NOT MATCHED THEN INSERT (BrandId, Name, SortOrder, IsActive) VALUES (source.BrandId, source.ModelName, source.SortOrder, 1);
-- END VEHICLE CATALOG SEED
