-- WhatsApp chatbot tables
-- Run once against the production database (Neon/Postgres)

-- Pre-clients: contacts identified only by phone (not yet registered)
CREATE TABLE IF NOT EXISTS pre_clientes (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  phone           TEXT        NOT NULL UNIQUE,
  name            TEXT,
  email           TEXT,
  gdpr_consent    BOOLEAN     NOT NULL DEFAULT FALSE,
  gdpr_consent_at TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- WhatsApp conversation state (one row per phone number, overwritten each turn)
CREATE TABLE IF NOT EXISTS whatsapp_sessions (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  phone      TEXT        NOT NULL UNIQUE,
  flow       TEXT        NOT NULL DEFAULT 'general',  -- 'general' | 'vo'
  step       TEXT        NOT NULL DEFAULT 'start',
  context    JSONB       NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Leads generated by the WhatsApp bot (one per resolved conversation branch)
CREATE TABLE IF NOT EXISTS whatsapp_leads (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  phone          TEXT        NOT NULL,
  pre_cliente_id UUID        REFERENCES pre_clientes(id),
  user_email     TEXT,                          -- if matched to a CarsWise account
  tipo           TEXT        NOT NULL,          -- INFO|FOTOS|FINANCIACION|VISITA|RESERVA|BUSQUEDA|RENTING|TASACION|SERVICIO|INCIDENCIA|ASESOR|OTRA
  sub_tipo       TEXT,                          -- TALLER|SEGURO|GARANTIA|TRAMITACION|OTRO (for SERVICIO)
  sub_fuente     TEXT,                          -- coches.net|autoscout24|wallapop|motor.es|otro portal
  oferta_id      TEXT,
  criterios      JSONB       NOT NULL DEFAULT '{}',
  prioridad      TEXT        NOT NULL DEFAULT 'normal',  -- normal | alta
  estado         TEXT        NOT NULL DEFAULT 'nuevo',   -- nuevo | asignado | resuelto
  transcript     JSONB       NOT NULL DEFAULT '[]',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS whatsapp_leads_phone_idx     ON whatsapp_leads(phone);
CREATE INDEX IF NOT EXISTS whatsapp_leads_tipo_idx      ON whatsapp_leads(tipo);
CREATE INDEX IF NOT EXISTS whatsapp_leads_estado_idx    ON whatsapp_leads(estado);
CREATE INDEX IF NOT EXISTS whatsapp_leads_created_idx   ON whatsapp_leads(created_at DESC);
