-- --------------------------------------------------------------------------
-- 0005 · Las claves prestadas
--
-- Cinco tablas se identificaban por algo que no es suyo o que cambia:
--
--   · `moveadvisor_user_invoices.id`   era el identificador de la sesión de
--     **Stripe** (`cs_test_a1rey…`). Nuestra factura se llamaba como la llamó
--     otro. El día que se cambie de pasarela, o que Stripe cambie de formato,
--     nuestras facturas se llaman como el proveedor que ya no usamos.
--   · `erp_staff_passwords.email`      y
--   · `moveadvisor_user_preferences.user_email`: la clave es un correo. Cambiar
--     el correo de alguien no es corregir un dato, es perder su fila.
--   · `erp_vendedores_marketplace.nombre`: la clave es un nombre. Corregir una
--     tilde crea un vendedor nuevo y deja el viejo ahí.
--   · `market_alerts` se identificaba por (id, correo), lo mismo pero a medias.
--
-- La regla que se aplica: **la clave es nuestra, no cambia y no significa
-- nada**. El correo, el nombre y la referencia de Stripe siguen estando, como
-- lo que son: datos de la fila, con su índice único para que se siga buscando
-- por ellos igual de rápido y para que los `ON CONFLICT` que ya existen sigan
-- funcionando sin tocar una línea de código.
--
-- Las cinco tablas tienen entre 0 y 2 filas. Es el momento más barato que va a
-- haber para esto.
-- --------------------------------------------------------------------------

-- ── 1 · Las contraseñas del equipo ────────────────────────────────────────

ALTER TABLE erp_staff_passwords DROP CONSTRAINT IF EXISTS erp_staff_passwords_pkey;
ALTER TABLE erp_staff_passwords ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE erp_staff_passwords ADD CONSTRAINT erp_staff_passwords_pkey PRIMARY KEY (id);
-- El correo sigue siendo único: `ON CONFLICT (email)` no se entera del cambio.
ALTER TABLE erp_staff_passwords ADD CONSTRAINT ux_staff_passwords_email UNIQUE (email);

-- ── 2 · Las preferencias del cliente ──────────────────────────────────────

ALTER TABLE moveadvisor_user_preferences DROP CONSTRAINT IF EXISTS moveadvisor_user_preferences_pkey;
ALTER TABLE moveadvisor_user_preferences ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE moveadvisor_user_preferences ADD CONSTRAINT moveadvisor_user_preferences_pkey PRIMARY KEY (id);
ALTER TABLE moveadvisor_user_preferences ADD CONSTRAINT ux_preferencias_correo UNIQUE (user_email);

-- ── 3 · Los vendedores del marketplace ────────────────────────────────────

ALTER TABLE erp_vendedores_marketplace DROP CONSTRAINT IF EXISTS erp_vendedores_marketplace_pkey;
ALTER TABLE erp_vendedores_marketplace ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE erp_vendedores_marketplace ADD CONSTRAINT erp_vendedores_marketplace_pkey PRIMARY KEY (id);
ALTER TABLE erp_vendedores_marketplace ADD CONSTRAINT ux_vendedores_nombre UNIQUE (nombre);

-- ── 4 · Las alertas de mercado ────────────────────────────────────────────
--
-- Se identificaban por (id, correo). El identificador ya era único por su
-- cuenta; el correo estaba ahí para no tener que fiarse de él. Ahora manda el
-- identificador y la pareja se queda como índice único, que es lo que usa el
-- `ON CONFLICT (id, user_email)` de alertsStore.js.

ALTER TABLE market_alerts DROP CONSTRAINT IF EXISTS market_alerts_pkey;
ALTER TABLE market_alerts ADD CONSTRAINT market_alerts_pkey PRIMARY KEY (id);
ALTER TABLE market_alerts ADD CONSTRAINT ux_alertas_id_correo UNIQUE (id, user_email);
CREATE INDEX IF NOT EXISTS ix_alertas_correo ON market_alerts (user_email);

-- ── 5 · Las facturas, que se llamaban como Stripe ─────────────────────────
--
-- Lo de fuera pasa a `referencia_externa`, que es lo que es: la referencia con
-- la que lo conoce quien nos lo mandó —Stripe, o el lead de una rectificativa—.
-- Sigue siendo única, porque es la que evita emitir dos veces la misma factura
-- cuando un webhook llega repetido, y eso no puede perderse.

ALTER TABLE moveadvisor_user_invoices ADD COLUMN IF NOT EXISTS referencia_externa TEXT;

UPDATE moveadvisor_user_invoices
   SET referencia_externa = id
 WHERE referencia_externa IS NULL OR referencia_externa = '';

ALTER TABLE moveadvisor_user_invoices
  ADD CONSTRAINT ux_facturas_referencia_externa UNIQUE (referencia_externa);

-- Y a partir de aquí la clave la ponemos nosotros.
ALTER TABLE moveadvisor_user_invoices ALTER COLUMN id SET DEFAULT gen_random_uuid()::text;

/*
 * La fila que ya había se rebautiza.
 *
 * Solo las que llevan un identificador que se ve que es de Stripe: `cs_` es una
 * sesión de pago, `in_` una factura suya, `pi_` un intento de cobro. Las que ya
 * tenían un identificador nuestro —`rect-…`, `dep-…`— se quedan como están: son
 * nuestros y no molestan.
 *
 * Nadie apunta a esta tabla con una clave ajena, así que cambiar el valor no
 * deja nada colgando. Y el PDF no se pierde: su dirección va en la fila, y el
 * nombre del fichero sale del número de factura, no del identificador.
 */
UPDATE moveadvisor_user_invoices
   SET id = gen_random_uuid()::text
 WHERE referencia_externa ~ '^(cs_|in_|pi_|sub_|cus_)';

COMMENT ON COLUMN moveadvisor_user_invoices.referencia_externa IS
  'Con qué referencia conoce esta factura quien la originó (Stripe, un lead). No es la clave.';
